name: navcat
description: "navcat is a dart navigation mesh to construction and query model for floor-based navigation."
version: 0.0.1
homepage: https://github.com/Knightro63/navcat/

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
