const List<String> filesJson = [
  'area_costs',
  'area_filters',
  'chunky_tri_mesh',
  // 'crowd_simulation',
  // 'custom_gltf_navmesh',
  // 'custom_navmesh_generation',
  // 'doors_and_keys',
  // 'dynamic_navmesh',
  // 'dynamic_obstacles',
  // 'find_diverse_paths',
  // 'find_nearest_poly',
  // 'find_node_path',
  // 'find_path',
  // 'find_random_point',
  // 'find_shortest_paths',
  // 'find_smooth_path',
  // 'find_straight_path',
  // 'flood_fill_pruning',
  // 'flow_field_pathfinding',
  // 'fps_dynamic_navmesh',
  // 'mark_compact_heightfield_areas',
  // 'move_along_surface',
  // 'multiple_agent_sizes',
  // 'navmesh_constrained_character_controller',
  // 'off_mesh_connections',
  // 'rasterize_filled_volume',
  // 'raycast',
  'solo_navmesh',
  // 'tiled_navmesh',
  // 'upload_model'
];
